### ISSUE TITLE
Redirects succesfully to firefox, but uses bing

### ISSUE THREAD

**Issue by onebeastchris** [AveYo/fox#15]
Hey! First off - ChrEdgeFkOff works wonderfully. Opens all the searches in firefox now. But it uses bing to search them - is there a way to get rid of bing? All the methods i've seen so far would involve turning web search off entirely, but it's too useful -

If it's not possible, it's alright - just thought i'd ask ^^

**Comment by AveYo** [comment]
I know, I use it myself 🥇 
There are multiple addons for firefox / librewolf to redirect bing, for example:
https://addons.mozilla.org/en-US/firefox/addon/bingtogoogle/
https://addons.mozilla.org/en-US/firefox/addon/bingtoduckduckgo/

Or you could use an alternative to this script with built-in redirects:
https://github.com/rcmaehl/MSEdgeRedirect 
https://github.com/HarshalKudale/NoMoreEdge

**Comment by onebeastchris** [comment]
Thank you so much - I'll try the other script since that has a few more functionality that I'll probably use too ^^
thank you again for a quick & insightful response!
