### ISSUE TITLE
Defender flags ChrEdgeFkOff as trojan: Wacatac.h!ml

### ISSUE THREAD

**Issue by dgriffith0** [AveYo/fox#16]
Window 11 defender is flagging the ChrEdgeFkOff as trojan Wacatac.h!ml after running and then removes it breaking the search.

**Comment by AveYo** [comment]
Yeah this just started. An automated false-positive detection.  
I already did the best I could few months ago to tame Defender and worked so far ;(  
What's left for me to do is probably to have a cmd window briefly shown, which is an annoyance.  
What you can do is to report a False Positive to microsoft:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by AveYo** [comment]
Pushed an update with a pure batch version.
So the command window will briefly flash when doing searches 👎  
Let's see if it's just Defender being dumber than a rock, or it's also malicious intent, specifically targeting the redirector.

**Comment by AveYo** [comment]
Command window flashing no more 🥇

**Comment by akuropka** [comment]
@AveYo, trying to download the github ZIP leads to detection of the supposed trojan:
![20221004_125731](https://user-images.githubusercontent.com/22570574/193802206-fd65d3c7-aa1a-444a-9b8f-ae2b625dce92.png)
![20221004_125715_ApplicationFrameHost](https://user-images.githubusercontent.com/22570574/193802225-e1be1522-fa0d-4fe6-a041-64face120ca5.png)

**Comment by AveYo** [comment]
It's obviously a false-positive.  
Download the script you need directly i.e. view [OpenWebSearch.cmd](https://github.com/AveYo/fox/blob/main/OpenWebSearch.cmd) - Raw - Save As. Can also just copy the text directly into a powershell window.

**Comment by akuropka** [comment]
Yeah, that works of course.
I was just getting the impression the issue may have been resolved that's why I noted this.

**Comment by AveYo** [comment]
Defender is a simpleton.
