### ISSUE TITLE
Edge update residue in fresh install of 22H2

### ISSUE THREAD

**Issue by terrytw** [AveYo/fox#18]
Hi, I recently fresh installed 22H2 using official ISO. Ran edge removal, the edge update app is still present.

And after an update, Edge actually come back.
![image](https://user-images.githubusercontent.com/24227628/192137281-1799b88a-e18e-4af5-9bfe-45a48e38f964.png)

**Comment by FadeMind** [comment]
Seems to be more complicated here. Edge have status like MS Store - not removable at all. 
Scripts does nothig (only purge WebView2 Runtime), does not touch in any Edge. 

![20220925-1664124042](https://user-images.githubusercontent.com/9846948/192154945-92b378b1-538a-49a3-bcda-aee2711361ae.png)

![20220925-1664124153](https://user-images.githubusercontent.com/9846948/192155033-6f6e5d74-9e83-43f2-b9e6-c2cc9665520d.png)

Even Uninstaller have only Repair option only. 

![20220925-1664124317](https://user-images.githubusercontent.com/9846948/192155165-a83230de-8247-428f-9cc7-20b7e97d29eb.png)

MSEdgeRedirect thanksfully works well as expected.

**Comment by AveYo** [comment]
Cannot confirm on release 22621. It removes it just fine.

**Comment by GuyWhoHatesEdge** [comment]
> Cannot confirm on release 22621. It removes it just fine.

The tool does remove Edge Update & Edge WebView2 for me too. But windows aggressively re-installs them days later. :(
Edge itself stays uninstalled fortunately.

**Comment by AveYo** [comment]
If you use Beta or Dev channel Windows 11, any new build is essentially an in-place upgrade/repair so it will restore whatever it is missing.   

So use release channel. Monthly Cumulative Updates generally do not bring it back.

Either way, it's trivial to remove again ;)

**Comment by GuyWhoHatesEdge** [comment]
> If you use Beta or Dev channel Windows 11, any new build is essentially an in-place upgrade/repair so it will restore whatever it is missing.
> 
> So use release channel. Monthly Cumulative Updates generally do not bring it back.
> 
> Either way, it's trivial to remove again ;)

Unsure if you misread my message, I’m using windows 10 home not windows 11/windows 11 dev.

And I re-downloaded your tool recently to remove the edge update & webview programs. But windows 10 added them back a day or two after.

**Comment by terrytw** [comment]
> > If you use Beta or Dev channel Windows 11, any new build is essentially an in-place upgrade/repair so it will restore whatever it is missing.
> > So use release channel. Monthly Cumulative Updates generally do not bring it back.
> > Either way, it's trivial to remove again ;)
> 
> Unsure if you misread my message, I’m using windows 10 home not windows 11/windows 11 dev.
> 
> And I re-downloaded your tool recently to remove the edge update & webview programs. But windows 10 added them back a day or two after.

Please open another issue if your problem is different than mine.

**Comment by terrytw** [comment]
I tried the same installation in a VM, it seems to be working just fine now. Weird....
