### ISSUE TITLE
Edge Update & Edge WebView2 Runtime reinstall themselves.

### ISSUE THREAD

**Issue by ghost** [AveYo/fox#19]
Using windows 10 home. Not windows 11/windows 11 dev. These two programs reinstall themselves after a few days when removed using this tool. I recently downloaded this tool to remove them again and they have come back. Darn edge.

![image](https://user-images.githubusercontent.com/114882400/193490316-7c9366d9-9fd9-4458-8901-b1a2e0211cb4.png)

**Comment by AveYo** [comment]
That only happens on a repair-install or feature update (going from 22H1 to 22H2 for example).
Nothing to do about that, it's a can of worms to hinder it (i.e. losing the possibility to repair)
