### ISSUE TITLE
ChrEdgeFKoff issue: Permission denied with Admin

### ISSUE THREAD

**Issue by JsephGriff** [AveYo/fox#2]
When attempting to run your script as a .cmd with admin permissions given, the following output occurs. Running the script again results in the same output, instead of undoing any changes made in the failed process.

Exception calling "WriteAllText" with "2" argument(s): "Access to the path 'C:\WINDOWS\system32\ChrEdgeFkOff.vbs' is
denied."
At line:15 char:86
+ ... ey 'Debugger' $cmd -force -ea 0; [io.file]::WriteAllText($file, $vbs)
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

**Comment by AveYo** [comment]
you probably have controlled folders enabled in windows defender or some other av, blocking write access to that system path  
so find a way to allow it in your av software, or temporarily disable it
I've updated the script to use programdata instead, might be a less strictly protected folder in lame av / configurations
