### ISSUE TITLE
how to pass an argument when running OpenWebSearch?

### ISSUE THREAD

**Issue by ghost** [AveYo/fox#20]
Hey,
I am not that tech savvy. How to pass an argument when running OPenWebSearch?

**Comment by AveYo** [comment]
The script automatically toggles between installed and removed state just by running it again.
That's how you use it, tech savvy or not.

The command line arguments `install` and `remove` are meant to be used from other scripts to force install or remove.

As for how to do it manually, open explorer to the script location, then `Ctrl`+`L` to focus address bar, then enter `OpenWebSearch install` or `OpenWebSearch.cmd remove` and the script will do that action and quit immediately without printing anything to the console.

While installed, you don't have to do anything. Just use windows start menu web search, widgets, help and any `microsoft-edge:` links that were forcefully opened in edge, are gonna open in your default browser, assuming you've set one (makes no sense to use this script if the default browser is still edge).

**Comment by direrFlood** [comment]
you are tech genius

**Comment by bigplayer-ai** [comment]
how can I run this with output on terminal/console?
