### ISSUE TITLE
Calling Edge_Removal from another batch file

### ISSUE THREAD

**Issue by SamHills** [AveYo/fox#22]
I need to run Edge_Removal from another batch file which performs all the configuration changes needed to set up a new computer.
To do this, everything must run smoothly without operator interaction of any kind unless an error occurs.
Please add a "Nopause" parameter, which will specify that Edge_Removal will exit quietly without any operator interaction if no error occurs, and without leaving any secondary command or PowerShell windows open.
Also, it should set ERRORLEVEL appropriately on exit so the calling file can know whether or not an error occurred.  In my files, I use Exit /B 0 (batch) / EXIT 0 (PS) if the file ran successfully and EXIT /B 2 (cmd) / EXIT 2 (PS) if the file ran but threw an error and waited for the user to see it.  ERRORLEVEL 1 is thrown by caller if the file could not be run and the caller must pause to allow the operator to read the error message.

**Comment by AveYo** [comment]
Yea I've missed on this suggestion. A silent mode would be a good addition
