### ISSUE TITLE
Question: what is the difference between the preinstalled edge webview runtime and the one downloaded from microsoft website?

### ISSUE THREAD

**Issue by terrytw** [AveYo/fox#24]
Dear dev, thanks a lot for the scripts!

I want to ask a question about the difference between preinstalled edge webview runtime and the one downloaded from microsoft website:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Their names seems identical, but the one downloaded separately will not be removed by this script, so I presume that they are different?

The reason I am asking is that my company has this PTC windchill and creoviewer combo for viewing documents. It works with preinstalled webview runtime. If I run the script with `$also_remove_webview = 0`, it still works. If I run the script with `$also_remove_webview = 1`, it won't work afterwards, even if I install the edge runtime webview again using the installer downloaded from Microsoft website. 

It would be much apprecicated if you could provide some insights to this, maybe pointing to a place where I should look? Thank you!

**Comment by AveYo** [comment]
I suspect is no longer an issue - but the only difference is system-wide vs per-user - edge / webview installers supports installing as admin or as standard user so that could make the difference (so make sure you run the installers as admin)
