### ISSUE TITLE
Restore edge

### ISSUE THREAD

**Issue by Fail-gh** [AveYo/fox#25]
There's a way to restore edge after using Edge_Removal.bat?

**Comment by RafeeDaBoy** [comment]
> I found a permanent solution
> 
> The Edge_Removal script adds a registry key that specifically blocks C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
> 
> Open regedit and delete HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe\0

[From here](https://github.com/ChrisTitusTech/winutil/issues/340#issuecomment-1450087676)

**Comment by AveYo** [comment]
for reference, all you have to do is run OpenWebSearch.cmd it should say (if not, run again)
` OpenWebSearch Redux  REMOVED  run again to install`  

reason being OpenWebSearch is included with Edge_Removal
