### ISSUE TITLE
Recent updates prevent Edge from uninstalling

### ISSUE THREAD

**Issue by WayneSherman** [AveYo/fox#26]
MS Edge is an absolute abomination and I do not want it on any of the systems I own or administer.  So thank you for your efforts in developing this removal script.

Testing on Windows 10 Pro 21H2 last updated 2022-May, the 2021-Dec-26 "[Edge_Removal.bat](https://github.com/AveYo/fox/blob/96e4d1439fd76f5131c220d4b9985ac81416d082/Edge_Removal.bat)" works nicely.  It completely removes Edge:
- Settings "Add/Remove Programs" - Edge is no longer listed
- Control Panel | Programs and Features (uninstall a program) - Edge is no longer listed
- "C:\Program Files (x86)\Microsoft\"  - Edge folder are gone
- Edge icons are gone from the start menu and desktop

Sometime between 2022-May and Oct, Microsoft must have updated Edge so that the older script no longer works (tested on Win10 Pro 21H2 updated Oct 03).  I tested the most recent "Edge_Removal.bat" [from the main branch](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) and it also does not work.  The latest script does render the start menu and desktop icons non-functional, but Edge still is present:
- Settings "Add/Remove Programs" - Edge is still in the list
- Control Panel | Programs and Features (uninstall a program) - Edge is still in the list
- "C:\Program Files (x86)\Microsoft\"  - Edge folders are still present
- Edge icons are present in the start menu and desktop (but don't work)
- Edge can still be launched via "C:\Program Files (x86)\Microsoft\EdgeCore\107.0.1418.42\msedge.exe"

**Comment by WayneSherman** [comment]
Also tested on Windows 11 Pro 21H2:
- Updated 2022-Mar, Edge removal works. (Edge 99.0.1150.55 )
- Updated 2022-Nov, Edge removal does NOT work. (Edge 107.0.1418.42)

**Comment by Jamskijam** [comment]
https://github.com/ShadowWhisperer/Remove-Edge-Chromium/issues/9#issuecomment-1356898491

**Comment by Rafee-M** [comment]
It currently works. Tested on Windows 10 Pro 22H2

**Comment by AveYo** [comment]
> https://gist.github.com/ave9858/c3451d9f452389ac7607c99d45edecc6

Thanks, I already had a fix but haven't published it as I can't test upgrade / repair scenarios atm.
Pushed an update anyway.

**Comment by WayneSherman** [comment]
Thank you guys for your work on an Edge removal script.

I tested the script from [ave9858](https://gist.github.com/ave9858)/[Uninstall Edge.md](https://gist.github.com/ave9858/c3451d9f452389ac7607c99d45edecc6). It works to cleanly remove Edge on a recent Windows 10 21H2 VM.

But the latest version of [Edge_Removal.bat](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) is not removing Edge on the same test system.  And if I run the new version once and then run the previous version of Edge_Removal.bat right after, that works for removing Edge.

**Comment by AveYo** [comment]
My love for Edge is increasing day after day!  
I am currently using a potato and it works here, but don't have space for a reinstall / vm atm.  
Really want to nail this bastard again!

**Comment by AveYo** [comment]
So there was a conflict with having OpenWebSearch installed prior to Edge_Removal.
Fixed!

**Comment by AveYo** [comment]
@Ammako, I kill processes not once, but twice! Specifically to prevent race conditions.
I guess I need to expand the list, or just do it one extra time ;)  

I always recommended reinstalling Edge and Webview if having issues.  
I should add it to the script itself at the end just like the `getfirefox` command.  
`getedge` & `getwebview` to download the setups from microsoft

Appreciate your feedback!

**Comment by WayneSherman** [comment]
For my testing this uninstall issue has been generally fixed since this commit:

2023.07.08 fixed:  https://github.com/AveYo/fox/commit/950f1d51b57a932e316de5c584165aa100928e80

Tested on Win10 and Win11.  On Win10 the script outputs these items as uninstalled:
```
Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe
Microsoft.MicrosoftEdge_44.19041.1266.0_neutral__8wekyb3d8bbwe
Microsoft.MicrosoftEdge.Stable_116.0.1938.69_neutral__8wekyb3d8bbwe
Microsoft.Win32WebViewHost_10.0.19041.1023_neutral_neutral_cw5n1h2txyewy

```
