### ISSUE TITLE
After running OpenWebSearch Install, Edge is not opening 

### ISSUE THREAD

**Issue by bigplayer-ai** [AveYo/fox#27]
Hey,
I want to change my default browser without disabling edge completely. When I run OpenWebSearch edge stops openning when trying to open its shortcut.
How can I fix this?

**Comment by rcmaehl** [comment]
Can repo as of Edge 109.0.1518.61.

**Comment by bigplayer-ai** [comment]
what does repo mean?

**Comment by rcmaehl** [comment]
> what does repo mean?

Reproduce. I forgot an r

**Comment by bigplayer-ai** [comment]
#28 experience the same issue

**Comment by CaseyKazan** [comment]
Thanks for the reply. But I don't know what this means to do: "Can repro[duce] as of Edge 109.0.1518.61"?

**Comment by CaseyKazan** [comment]
Hi, is anybody here to help? I haven't received a response in three weeks. Any assistance is appreciated, thank you!

**Comment by PrincessAkira** [comment]
![image](https://user-images.githubusercontent.com/45071533/224102472-2a1b794f-eb26-446a-aa5e-b912a2ca3554.png)
THis is what happens everytime you start edge btw

**Comment by Rafee-M** [comment]
Are the changes made by OpenWebSearch registry edits and stuff or is there a service/program running in the background?

**Comment by vonDubenshire** [comment]
> 

thanks, put off uninstalling this stuff b\c of this issue, thanks a lot
