### ISSUE TITLE
 Ran ChkrEdgeFkOff.cmd but Now I can't Open Edge at All.

### ISSUE THREAD

**Issue by CaseyKazan** [AveYo/fox#28]
Hi, I just installed this script a few days ago. Wow, works great!

Except today I *_wanted_* to use Edge and it won't work! What's the deal? Did it delete Edge altogether? Can I fix this without deleting (running the command again) the whole command? Obviously, I am not a Windows programmer! :-)

Please help! Thank you!

**Comment by bigplayer-ai** [comment]
check #27
