### ISSUE TITLE
[Query] Is OpenWebSearch running in the background?

### ISSUE THREAD

**Issue by Rafee-M** [AveYo/fox#30]
I was just wondering if it's running in the background or if `OpenWebSearch.cmd` and/or `ie_to_edge_stub.exe` is called only when a link is opened from Windows search?

**Comment by rcmaehl** [comment]
> I was just wondering if it's running in the background or if `OpenWebSearch.cmd` and/or `ie_to_edge_stub.exe` is called only when a link is opened from Windows search?

I can answer this for you. It will only run when Windows Web Search calls Microsoft Edge. All modern solutions (OpenWebSearch, Wedge, MSEdgeRedirect) use Image File Execution Options (IFEO) to Intercept Edge, this means it will only run if a new microsoft edge process is launched. There are other methods such as MSEdgeRedirect's Service Mode which don't use IFEO as it requires admin rights, but non-IFEO methods are not as reliable.

**Comment by Rafee-M** [comment]
Thanks a lot for the information, it cleared it up. I really appreciate it!

And if I understand correctly non-IFEO methods such as MSEdgeRedirect's `Service Mode` may run in the background, but its `Active Mode` and OpenWebSearch run only when Microsoft Edge is called due to using IFEO.

**Comment by rcmaehl** [comment]
> Thanks a lot for the information, it cleared it up. I really appreciate it!
> 
> And if I understand correctly, non-IFEO methods such as MSEdgeRedirect's `Service Mode` may run in the background, but its `Active Mode` and OpenWebSearch run only when Microsoft Edge is called due to using IFEO?

Correct!

**Comment by Rafee-M** [comment]
Thanks a lot for your time and information!
