### ISSUE TITLE
 Edge_Removal.bat Seems broken in build 22621.1465 

### ISSUE THREAD

**Issue by GrassBlock1** [AveYo/fox#31]
As title mentioned, I can't remove ms edge through [Edge_Removal.bat](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) in this build.

I run this for two times. The first time it lists the packages that seems to be removed but it didn't.
The second time as the picture below:
![图片](https://github.com/AveYo/fox/assets/46253950/ce3889e3-6e36-4020-847b-d2888d57f286)

**Comment by AveYo** [comment]
fully fixed with 2023.07.08
better late than never ;)
sorry
