### ISSUE TITLE
Does Uninstalling Edge browser affects future update like LCU of 2024 to 2032 On Windows 10 Iot Enterprise LTSC 2021

### ISSUE THREAD

**Issue by RaphaelZB143** [AveYo/fox#32]
I'm afraid that When the lcu of 2024 to 2032 is failing because of edge browser. Windows 10 Iot LTSC 2021

**Comment by AveYo** [comment]
Already considered. All LCU's install fine, feature upgrades install fine.  
If there's gonna be an issue, I'm sure we can work around it.
