### ISSUE TITLE
"OneClickSearch redux" script does not work anymore since Firefox 117

### ISSUE THREAD

**Issue by dartraiden** [AveYo/fox#34]
Tested on [Firefox 117 RC2](https://download-installer.cdn.mozilla.net/pub/firefox/candidates/117.0-candidates/build2/)

**Comment by AveYo** [comment]
OpenWebSearch script does not care about what browser is set as default.
Since it's a Release Candidate it might be bugged in the way it sets itself as the default browser.
Should report to Mozilla asap.

**Comment by dartraiden** [comment]
Not OpenWebSearch. I'm talking about OneClickSearch - https://www.reddit.com/r/firefox/comments/ls0ffy/oneoffsrefresh_redux_single_click_search_icons_in/

**Comment by dartraiden** [comment]
116:

![WindowsSandboxClient_P5feTrYNS0](https://github.com/AveYo/fox/assets/5046855/c0a0843a-3b34-4ca9-afff-e9ea03bed9d0)


117:

![mstsc_mEvhxEJwJi](https://github.com/AveYo/fox/assets/5046855/87dab7cb-4135-4136-aa3b-8274a7c0f0af)

**Comment by AveYo** [comment]
Sorry :( I totally forgot that exists and assumed it's a typo.
Guess it was a matter of time..
Will have to test it myself so I don't have an answer for you atm

**Comment by dartraiden** [comment]
It works, thanks!
