### ISSUE TITLE
2023.08.28 Edge_Removal redux! leaves some items installed

### ISSUE THREAD

**Issue by WayneSherman** [AveYo/fox#35]
Thanks for your ongoing work on the Edge removal script.  The previous version (2023.07.08) also uninstalls Edge Update and  Microsoft.MicrosoftEdgeDevToolsClient.  The most recent version does not uninstall Edge Update or  Microsoft.MicrosoftEdgeDevToolsClient.

Tested "2023.08.28 Edge_Removal redux!" ( https://github.com/AveYo/fox/commit/dff701916cae25abf77f4d994268ec964806d5a0 )

**Testing on Win10 IoT Enterprise 21H2**
Script outputs these two items:
```
C:\Program Files (x86)\Microsoft\Edge\Application\116.0.1938.69\Installer\setup.exe --msedge --uninstall --force-uninstall --system-level
Microsoft.MicrosoftEdge_44.19041.1266.0_neutral__8wekyb3d8bbwe

```
This folder is still present with files in it:
"C:\Program Files (x86)\Microsoft\EdgeUpdate"
(also still present as "Microsoft Edge Update" in Add/Remove programs)

(Get-AppxPackage).Name still lists "Microsoft.MicrosoftEdgeDevToolsClient"

**Testing on Win11 Pro**
Script outputs these items:
```
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\115.0.1901.203\Installer\setup.exe --msedgewebview --uninstall --force-uninstall --system-level
C:\Program Files (x86)\Microsoft\Edge\Application\116.0.1938.69\Installer\setup.exe --msedge --uninstall --force-uninstall --system-level
Microsoft.MicrosoftEdge_44.22621.2134.0_neutral__8wekyb3d8bbwe
MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
MicrosoftWindows.Client.WebExperience_423.13900.0.0_x64__cw5n1h2txyewy

```
This folder is still present with files in it:
"C:\Program Files (x86)\Microsoft\EdgeUpdate"
(also still present as "Microsoft Edge Update" in Add/Remove programs)

(Get-AppxPackage).Name still lists "Microsoft.MicrosoftEdgeDevToolsClient"

This file still exists:
"C:\Program Files (x86)\Microsoft\EdgeCore\99.0.1150.55\EBWebView\x64\EmbeddedBrowserWebView.dll"
(this is also left behind with the previous version of removal script from 2023.07.08)

On at least one occasion I had to run the script twice to get Edge to uninstall.  Maybe something was running that blocked the removal the first time.

**Comment by WayneSherman** [comment]
For reference, the previous uninstall script from 2023-97-08 when running on Win10 outputs these items as uninstalled:
```
Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe
Microsoft.MicrosoftEdge_44.19041.1266.0_neutral__8wekyb3d8bbwe
Microsoft.MicrosoftEdge.Stable_116.0.1938.69_neutral__8wekyb3d8bbwe
Microsoft.Win32WebViewHost_10.0.19041.1023_neutral_neutral_cw5n1h2txyewy
```

**Comment by AveYo** [comment]
The change was intended.  

Microsoft.MicrosoftEdgeDevToolsClient is just the html resources cache for the f12 dev tools, with no binaries. Most times it was not even uninstalling, would re-appear after running the script again.  

EdgeUpdate will attempt a cleanup, but that can fail if stuff is running. For example mmc would load an edge dll if available, so that means any group policy / scheduled tasks / events etc windows would be blocking it. But it will automatically mark those folders for delete on next reboot, and you haven't checked that.

**Comment by AveYo** [comment]
Also note that on a fresh clean install removing edge does not work. 
It will take some updates to begin working. 
Can however enter `edge` once the script finished and edge icons are still there, it will forcefully update it with the online version - then run the script again. Haven't explored an automated workaround yet.

**Comment by WayneSherman** [comment]
> The change was intended.
> Microsoft.MicrosoftEdgeDevToolsClient is just the html resources cache for the f12 dev tools, with no binaries. Most times it was not even uninstalling, would re-appear after running the script again.

For my testing of the previous script (from July), dev tools client uninstalls and stays uninstalled.

> EdgeUpdate will attempt a cleanup, but that can fail if stuff is running...But it will automatically mark those folders for delete on next reboot

After running the new new script and a reboot, Edge update is still installed.  I ran the script a second time after rebooting, but no change.  Running the previous script from July uninstalls Edge Update without a reboot.

> Also note that on a fresh clean install removing edge does not work.

Tested with:
Win10 fully updated as of today
Win10 updated to 2023-July-27
Win11 updated to 2023-Aug-21.

**Comment by WayneSherman** [comment]
Also I just noticed that Microsoft.Win32WebViewHost is not uninstalling with the new script.  ($also_remove_webview = 1)

**Comment by AveYo** [comment]
The relevant change is that the previous iteration was brute-forcing calling setup regardless of it being for edge or webview, actually causing issue with EdgeUpdate being called with invalid command line as per logs. 
Now that it is done "properly", seems not fine for your environment. My tests are done on latest 10 and latest 11 (Canary). I've left testing on other versions to you guys, so thanks for the report!  
Will investigate.

**Comment by AveYo** [comment]
Tested 22621, and was able to reproduce the issue after 5 snapshot runs.  
So I'm restoring the previous order (running appx removal first, then the setup) and also re-add dev tools for removal (even if it does not work anymore in Canary).
Thanks!

**Comment by WayneSherman** [comment]
Test results for [2023.09.08](https://github.com/AveYo/fox/commit/6100fe7aa4b184bf5a943fa9fde48822f4d8617b):
- Edge stable removal on Win10 IoT 21H2 LTSC fully updated (as of yesterday)
- Edge stable removal on Win11 Pro 22H2 fully updated (as of today)

Current removal script is improved, now "Microsoft.MicrosoftEdgeDevToolsClient" and "Microsoft Edge Update" are uninstalled.  :-)

**Win10 Script Output:**
```
Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe
Microsoft.MicrosoftEdge_44.19041.1266.0_neutral__8wekyb3d8bbwe
Microsoft.MicrosoftEdge.Stable_116.0.1938.69_neutral__8wekyb3d8bbwe
C:\Program Files (x86)\Microsoft\Edge\Application\116.0.1938.69\Installer\setup.exe --uninstall --msedge --system-level --verbose-logging --force-uninstall
```
**Win11 Script Output:**
```
Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
Microsoft.MicrosoftEdgeDevToolsClient_1000.22621.1.0_neutral_neutral_8wekyb3d8bbwe
Microsoft.MicrosoftEdge.Stable_116.0.1938.69_neutral__8wekyb3d8bbwe
Microsoft.MicrosoftEdge_44.22621.2215.0_neutral__8wekyb3d8bbwe
MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
MicrosoftWindows.Client.WebExperience_423.23500.0.0_x64__cw5n1h2txyewy
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\116.0.1938.69\Installer\setup.exe --uninstall --msedgewebview --system-level --verbose-logging --force-uninstall
C:\Program Files (x86)\Microsoft\Edge\Application\116.0.1938.69\Installer\setup.exe --uninstall --msedge --system-level --verbose-logging --force-uninstall
```

But on both test systems "Microsoft.Win32WebViewHost" is still not uninstalled.  The appx name needs to be "Win32WebViewHost" for it to be successfully removed.

**2023-07-08 version successfully removes Edge Web View:**
`if ($also_remove_webview -eq 1) {$remove_win32 += "Microsoft EdgeWebView"; $remove_appx += "Win32WebViewHost"}`

**2023-09-08 version does not remove Edge Web View:**
`if ($also_remove_webview -eq 1) {$remove_win32 += "Microsoft EdgeWebView"; $remove_appx += "WebExperience"}`

Does "WebExperience" have any parts of Edge in it?
https://support.microsoft.com/en-us/windows/how-to-update-the-windows-web-experience-pack-in-the-microsoft-store-a16c9bf1-f042-4dc9-a523-740cca1e1e60

**Comment by WayneSherman** [comment]
There are apparently two "web views" and the appx "Microsoft.Win32WebViewHost" is not the same as webview2.  Webview2 uses the new Edge (chromium based) and can be used for Desktop apps:
https://learn.microsoft.com/en-us/windows/apps/design/controls/web-view
https://learn.microsoft.com/en-us/microsoft-edge/webview2/

The older "web view" is based on the legacy Edge.  I suspect "Microsoft.Win32WebViewHost" is the same and is the "Web View" for UWP apps discussed here:
https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview?view=winrt-22621

**Comment by AveYo** [comment]
You're not supposed to indiscriminately butcher everything with 'Edge' in it.  

Check System32, there's plenty of Edge*.exe
EdgeHTML.dll library, replacing the former ie-based mshtml.dll, is needed by anything requiring a browser frame, both internally and 3rd party programs.

I see Win32WebViewHost & EdgeDevToolsClient as part of that, the skipping was intentional. 
Both marked system and non-removable, even if the tricks I've made manage to remove them from the appx catalog, does not mean it should be done. These are not abused by microsoft in any way, and have 
negligible storage size. And like I've said, tricks won't work in Canary anymore.  
And while EdgeDevToolsClient seems pretty safe to nuke, Win32WebViewHost might still be used by some older store app so I left it alone. Feel free to add it yourself in your copy (`$remove_appx += "WebExperience","Win32WebViewHost"`)

Focus should be on entirely optional standalone components that microsoft is actively using for undesirable purposes, mainly Edge Stable and it's Core and Webview2 clones, growing to be gigabytes in size and spreading like a virus on former winui inbox applications that get web-ified.

**Comment by WayneSherman** [comment]
>You're not supposed to indiscriminately butcher everything with 'Edge' in it.

Understood.  I decide what to remove and/or disable depending on the system use case (from embedded single purpose systems with little or no local human interaction to general use user desktop systems) 

>tricks won't work in Canary anymore.

Unfortunately it is a constant battle trying to make Windows work like you want.  For my daily driver I switched to Linux years ago so I don't have to deal with MS.

>Removing Widgets it's a bonus specific to 11, and is not guaranteed to succeed.

I remove Widgets (WebExperience) appx in other scripts.  For my use cases I prefer to stay specific to Edge in the Edge removal script.

Yes, the current script works and "Win32WebViewHost" can be removed elsewhere or with a simple edit if preferred.  Thanks for your work.

**Comment by AveYo** [comment]
Btw, for generic appx removal there's also [FORCE APPX UNINSTALL.bat](https://pastebin.com/A48aF1BF) where you can pick and choose what to remove in a GUI interface

**Comment by AveYo** [comment]
@WayneSherman, 
After more scenarios tested, EdgeUpdate often remains behind.  
Mostly when Edge was already removed and only WebView is installed atm. 
Seems hardcoded to clean itself up only after removing Edge, so I am now force cleaning it.
Obviously only doing it for `$also_remove_webview = 1`  
Thanks again for insisting with this issue and let me know if there's further issues.  

I also added back Win32WebViewHost for removal, haven't found a single app making use of it.
And in any case, added it to the `webview` reinstall command, it will restore it if available.
No idea why I was getting so hell-bent on playing it safe, when I have not seen or received any reports of adverse effects, sorry about that ;)

**Comment by WayneSherman** [comment]
> After more scenarios tested, EdgeUpdate often remains behind. Mostly when Edge was already removed and only WebView is installed atm. Seems hardcoded to clean itself up only after removing Edge

It seems the updater wants to stay if either Edge or webview2 are installed.   The "Evergreen" installer for webview2 also installs Edge Updater (and in my test a fully functional Edge browser):
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
(and if the installer is run as an unprivileged user then all Edge, webview2, and EdgeUpdater get installed into the user profile:
C:\Users\[user_name]\AppData\Local\Microsoft)

>...so I am now force cleaning it.

When manually deleting an installed program (versus running the uninstaller) it is difficult to find all the pieces (services, schedule tasks, registry entries).  For EdgeUpdater there are two services left over:
```
edgeupdate                                Automatic Microsoft Edge Update Service (edgeupdate)                                        
edgeupdatem                                  Manual Microsoft Edge Update Service (edgeupdatem)                                       

```

> I also added back Win32WebViewHost for removal, haven't found a single app making use of it. And in any case, added it to the `webview` reinstall command, it will restore it if available.

Thanks for that.

> No idea why I was getting so hell-bent on playing it safe, when I have not seen or received any reports of adverse effects, sorry about that ;)

No worries.  Thanks again.

**Comment by AveYo** [comment]
I'm aware, the script grabs edges from 'LocalApplicationData','ProgramFilesX86','ProgramFiles'
The scenario with Edge already removed and Webview present has no easy solution other than reinstalling Edge, and that's not desirable, so my forced cleanup is quite adequate.  

> When manually deleting an installed program (versus running the uninstaller) it is difficult to find all the pieces (services, schedule tasks, registry entries). For EdgeUpdater there are two services left over:
> 
> ```
> edgeupdate, Automatic,  Microsoft Edge Update Service (edgeupdate)
> edgeupdatem, Manual, Microsoft Edge Update Service (edgeupdatem)
> ```
It's just in the registry. 
Not my goal to turn into CCleaner, when most times it's cleaned automatically. 
But since I do it for the folders, uninstall entry and the tasks, adding the orphaned services too is not too much trouble for the next revision (it slipped my mind despite recently using scripts to block them). Thanks.

**Comment by WayneSherman** [comment]
It looks like you have been busy.   :-) 
Nice work on the clean removal of EdgeUpdate and other improvements.

One small issue on [line 144](https://github.com/AveYo/fox/blob/d599d630a85095b93c76ffa44d546eed06e2168b/Edge_Removal.bat#L144) where $PackageFamilyName is used.  It probably needs to be $appx.PackageFamilyName.

I didn't test all the cases, but did some simple removal, re-install, removal tests of Edge and EdgeWebView on Win10 (IoT 21H2), Win10 Pro 22H2 and Win11 Pro 22H2.

Only on Windows 10 IoT 21H2 (LTSC), do I get this error while removing the appx provisioned package:
```
Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
remove-appxprovisionedpackage : Remove-AppxProvisionedPackage failed. Error code = 0xc03f6508
At line:134 char:5
+     remove-appxprovisionedpackage -packagename $PackageName -online - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxProvisionedPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveAppxProvisionedPackageCommand
```
But it seems to remove it anyway.  The remove script from 2023-07-08 doesn't generate an error message, but I haven't figured out why yet.

**Comment by AveYo** [comment]
That's also by design. Before, all errors there were silenced and I would not know at a glance if there's an issue with a specific configuration, like your IoT LTSC.
And the removal was done via cmd /c dism.. while now the ps cmdlet is used, for consistency.

**Comment by WayneSherman** [comment]
> There's no PackageFamilyName in get-appxprovisionedpackage, that's why I'm determining it from the other get-appxpackage loop (it should never be orphaned, but who knows).

Yes, the first loop (iterating appx _provisioned_ package objects) has to lookup the appx PackageFamilyName (from the appx package objects), and it sets the variable $PackageFamilyName for each iteration:
`$PackageFamilyName = ($appxpackage |where {$_.Name -eq $appx.DisplayName}).PackageFamilyName `

But in the next loop (iterating appx package objects), $PackageFamilyName is stuck with the value from the last iteration of the previous loop.  $PackageFamilyName is not being set for each iteration in the second loop.  I am almost certain that is not what you intend.

Here are two suggestions on fixing it:
1) Change [line 144](https://github.com/AveYo/fox/blob/d599d630a85095b93c76ffa44d546eed06e2168b/Edge_Removal.bat#L144) to
    dism /online /set-nonremovableapppolicy /packagefamily:$appx.PackageFamilyName /nonremovable:0 >''
or
2) Change [line 141](https://github.com/AveYo/fox/blob/d599d630a85095b93c76ffa44d546eed06e2168b/Edge_Removal.bat#L141) to
 $PackageFullName = $appx.PackageFullName; $PackageFamilyName = $appx.PackageFamilyName
