### ISSUE TITLE
Kaspersky blocks ChrEdgeFkOff.vbs

### ISSUE THREAD

**Issue by Volt-Ampere** [AveYo/fox#4]
I tried putting the script on whitelist and setting exceptions and all that but Kaspersky Security Cloud keeps detecting the script as either HEUR:Trojan-Downloader.VBS.SLoad.gen or USD:DangerousObject.Multi.Generic

**Comment by AveYo** [comment]
I can't do anything about that. [Report false-positive to Kaspersky yourself](https://community.kaspersky.com/instructions-121/kaspersky-how-to-report-false-positive-22328)

What needs to be whitelisted:
file: `C:\ProgramData\ChrEdgeFkOff.vbs`
registry: `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe`
