### ISSUE TITLE
Can't update ChrEdge

### ISSUE THREAD

**Issue by alessio89g** [AveYo/fox#7]
Installing ChrEdgeFkOff.cmd and then going to Microsoft Edge Info Page (Edge Settings) in order to check updates, I get this:
error code 1: [0x80004005](https://go.microsoft.com/fwlink/?linkid=2068169&0x80004005) -- system level
If I uninstall ChrEdgeFkOff.cmd the update process works fine.
There is any way to redirect the ChrEdge links to the default browser without breaking updates?

**Comment by AveYo** [comment]
Under investigation.
You can try another solution like [MSEdgeRedirect](https://github.com/rcmaehl/MSEdgeRedirect) or [NoMoreEdge](https://github.com/HarshalKudale/NoMoreEdge)

**Comment by alessio89g** [comment]
NoMoreEdge produces the same problem as ChrEdgeFkOff;
MSEdgeRedirect in service mode solved my problem.
Thanks.

**Comment by AveYo** [comment]
should be fine with **v3**

**Comment by AveYo** [comment]
@alessio89g thanks for the feedback!
