### ISSUE TITLE
Edge fails to start

### ISSUE THREAD

**Issue by Wynadorn** [AveYo/fox#9]
A recent update might be causing Edge to break completely after running this under Windows 11
https://forums.somethingawful.com/showthread.php?threadid=4000582

When starting Edge it generates a Win32/Powessere.SA thread in defender

**Comment by AveYo** [comment]
> it seems all those billions poured into telemetry and machine learning by microsoft, google and av vendors are only used to "classify" user's private data,  
none trickled down into av heuristics so av's today are dumber than a rock, not discerning actually malicious stuff, even below the 90's era signature level. 
in the case of microsoft there's also **a strong fake positive bias**!

Already come up with a solution for the equally affected `Skip_TPM_Check_on_Dynamic_Update.cmd`
> av false & fake positive? reject humanity (powershell), return to monke (cmd) 
I plan to refactor this script as well sometime tomorrow
Thank you for your report!

**Comment by AveYo** [comment]
should be fine in **v3**
sorry for the long delay
